### ISSUE TITLE
Morning session peer to peer code review:

### ISSUE THREAD

**Issue by davidigbo** [Rishi-Mishra0704/awesome-books#2]
#You have done a great job and your project is already completed.
![StandingOvationGIF](https://user-images.githubusercontent.com/95672514/220275236-54377798-dba9-439f-9a5c-fe233cab5885.gif)

 - However, We suggest you deploy your Project.
 - This is optional, we think it will be a good practice if you style the project that will make you get used to your tools.

**Comment by AbdusSattar-70** [comment]
Hello @david30-maker, 
Thanks for reviewing and investing time to suggest.
I'm sorry for announcing that it was a medium wireframe project, that's why we didn't style anymore. resolved #2
